---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: ansible_push
  ansible_config: "test/ansible.cfg"
  idempotency_test: true
  diff: true

platforms:
  - name: ubuntu-16.04

verfier:
  name: inspec

suites:
  - name: default
    provisioner:
      playbook: "test/integration/default/ansible/playbook.yml"
