---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: ansible_playbook
  hosts: localhost
  require_ansible_repo: false
  require_ansible_omnibus: true
  ansible_version: 2.4.0.0

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
