---
driver:
  name: docker
  socket: unix:///var/run/docker.sock
  privileged: true
  use_sudo: false
  hostname: "simple"


provisioner:
  name: ansible_push
  chef_bootstrap_url: nil
  ansible_config: "test/ansible.cfg"
  idempotency_test: true
  diff: true


platforms:
  - name: ubuntu-16.04
    driver:
      run_command: /start
      run_options: --tty -e 'container=docker'
      privision_command:


verifier:
  name: inspec

suites:
  - name: default
    provisioner:
      playbook: "test/integration/default/ansible/playbook.yml"
