---
sudo: required

services:
  - docker

language: python
python: "2.7"

addons:
  apt:
    packages:
      - python-pip

env:
  - OS=ubuntu_xenial

before_install:
  - pip install ansible-galaxy-local-deps dcb==0.0.14
  - ansible-galaxy-local-deps-write

script:
  - >-
    dcb
    --upstreamgroup andrewrothstein
    --upstreamapp docker-ansible-role
    --pull ${OS}
    --write ${OS}
    --build ${OS}
    --push ${OS}
